# Dev-specific overrides
domain: the-fitness-arena-dev.duckdns.org
tlsSecret: gym-tls-dev

# Use 1 replica for dev
db:
  replicaCount: 1
booking:
  replicaCount: 1
membership:
  replicaCount: 1
notifier:
  replicaCount: 1
frontend:
  replicaCount: 1
