{{- if .Values.db.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-db
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: gym-db
  template:
    metadata:
      labels:
        app: gym-db
    spec:
      containers:
      - name: mysql
        image: {{ .Values.acr.name }}.azurecr.io/gym-db:{{ .Values.db.tag }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "gymrootpass"
        - name: MYSQL_DATABASE
          value: "gymapp"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: gym-db-service
spec:
  selector:
    app: gym-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
{{- end }}
