{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-{{ $name }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: gym-{{ $name }}
  template:
    metadata:
      labels:
        app: gym-{{ $name }}
    spec:
      containers:
      - name: gym-{{ $name }}
        image: {{ $.Values.acr.name }}.azurecr.io/{{ $svc.image }}:{{ index $.Values $name "tag" | default "latest" }}
        ports:
        - containerPort: {{ $svc.port }}
        {{- if $svc.env }}
        env:
        {{- range $svc.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- end }}
---
{{- end }}
