{{- if .Values.notifier.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-notifier
spec:
  replicas: {{ .Values.notifier.replicaCount }}
  selector:
    matchLabels:
      app: gym-notifier
  template:
    metadata:
      labels:
        app: gym-notifier
    spec:
      containers:
      - name: gym-notifier
        image: {{ .Values.acr.name }}.azurecr.io/gym-notifier:{{ .Values.notifier.tag }}
        ports:
        - containerPort: 4003
        env:
        - name: DB_HOST
          value: "gym-db-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "gymrootpass"
        - name: DB_NAME
          value: "gymapp"
---
apiVersion: v1
kind: Service
metadata:
  name: gym-notifier-service
spec:
  selector:
    app: gym-notifier
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003
  type: ClusterIP
{{- end }}
